--HeroSkin.xlsx
Cfg_HeroSkin = "HeroSkin"
G_CfgName2MainKey = G_CfgName2MainKey or {}
G_CfgName2MainKey[Cfg_HeroSkin] = "SkinId"
Cfg_HeroSkin_P_MainKey = "SkinId"
Cfg_HeroSkin_P = {
    SkinId = "SkinId",
    ItemId = "ItemId",
    HeroId = "HeroId",
    SkinName = "SkinName",
    SkinDes = "SkinDes",
    SkinVoice = "SkinVoice",
    SkinBP = "SkinBP",
    PNGPath = "PNGPath",
    PNGPathAnomaly = "PNGPathAnomaly",
    HalfBodyBGPNGPath = "HalfBodyBGPNGPath",
    FullBodyPNGPath = "FullBodyPNGPath",
    ChoosePNGPath = "ChoosePNGPath",
    FullBodyBGPNGPath = "FullBodyBGPNGPath",
    UnlockItemId = "UnlockItemId",
    UnlockItemNum = "UnlockItemNum",
    SuitType = "SuitType",
    SuitID = "SuitID",
    SuitPartList = "SuitPartList",
    MainPartID = "MainPartID",
    SuitIconPath = "SuitIconPath",
    PNGPathNormal = "PNGPathNormal",
    IsCanUnlock = "IsCanUnlock",
    HalfBodyHorPath = "HalfBodyHorPath",
}
