--HeroDisplayBoard.xlsx
Cfg_HeroDisplayBoardDefaultCfg = "HeroDisplayBoardDefaultCfg"
G_CfgName2MainKey = G_CfgName2MainKey or {}
G_CfgName2MainKey[Cfg_HeroDisplayBoardDefaultCfg] = "HeroId"
Cfg_HeroDisplayBoardDefaultCfg_P_MainKey = "HeroId"
Cfg_HeroDisplayBoardDefaultCfg_P = {
    HeroId = "HeroId",
    FloorId = "FloorId",
    RoleId = "RoleId",
    EffectId = "EffectId",
    StickerId_1 = "StickerId_1",
    PosX_1 = "PosX_1",
    PosY_1 = "PosY_1",
    ScaleX_1 = "ScaleX_1",
    ScaleY_1 = "ScaleY_1",
    Angle_1 = "Angle_1",
    StickerId_2 = "StickerId_2",
    PosX_2 = "PosX_2",
    PosY_2 = "PosY_2",
    ScaleX_2 = "ScaleX_2",
    ScaleY_2 = "ScaleY_2",
    Angle_2 = "Angle_2",
    StickerId_3 = "StickerId_3",
    PosX_3 = "PosX_3",
    PosY_3 = "PosY_3",
    ScaleX_3 = "ScaleX_3",
    ScaleY_3 = "ScaleY_3",
    Angle_3 = "Angle_3",
}
