---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2023/9/25 15:30
---
---
local ES_EnhanceExtractionTips = Class("Common.Framework.UserWidget")

local function GetInt(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsIntSimple(BlackBoard,Key)
    return Value
end

local function GetName(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsNameSimple(BlackBoard,Key)
    return Value
end

local function GetString(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsStringSimple(BlackBoard,Key)
    return Value
end

local function GetEnum(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsEnumSimple(BlackBoard,Key)
    return Value
end

local function GetFloat(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsFloatSimple(BlackBoard,Key)
    return Value
end

local function GetBool(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsBoolSimple(BlackBoard,Key)
    return Value
end

local function GetObject(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsObjectSimple(BlackBoard,Key)
    return Value
end


function ES_EnhanceExtractionTips:OnInit()

    if BridgeHelper.IsMobilePlatform() then
        if self.RootOverlay then
            self.RootOverlay:SetVisibility(UE.ESlateVisibility.Collapsed)
        end
        if self.BP_MobileTipButton then
            self.BP_MobileTipButton:SetVisibility(UE.ESlateVisibility.Collapsed)
        end

        if self.StrengthenButton then
            self.StrengthenButton:SetVisibility(UE.ESlateVisibility.Visible)
            self.BindNodes = {
                { UDelegate = self.StrengthenButton.OnClicked,				Func = self.OnStrengthenButtonClicked},
                --{ UDelegate = self.BP_MobileTipButton.OnClicked,				Func = self.OnMobileTipButtonClicked},
            }
        end
    end

	UserWidget.OnInit(self)
end

function ES_EnhanceExtractionTips:OnShow(InContext, InGenericBlackboard)
end



function ES_EnhanceExtractionTips:UpdateData(Owner, Count, BlackBoard)

    self:RemoveAllActiveWidgetStyleFlags()
    local bEnable = GetBool(BlackBoard, "EnableInteractive")
    local EnhanceState = GetInt(BlackBoard, "EnhanceState")
    self.BP_TitleTips.InputHint:SetVisibility(bEnable and UE.ESlateVisibility.Visible or UE.ESlateVisibility.Collapsed)
    self.TextBlock_Price:SetVisibility(EnhanceState == UE.EEnhanceTips.EnhanceTimesOut and UE.ESlateVisibility.Collapsed or UE.ESlateVisibility.SelfHitTestInvisible)
    local TipsId = GetEnum(BlackBoard, "TipsMessage")

    local Message = self.TipsContentList[TipsId]
    local TipsColor = self.TipsColorList[TipsId]

    --交互提示
    self.BP_TitleTips.Text_Making:SetText(Message)
    self.BP_TitleTips.Text_Making:SetColorAndOpacity(TipsColor)
    --价格
    self.TextBlock_Price:SetText(GetInt(BlackBoard, "EnhancePrice"))

    --是不是有效的物品
    local bIsValidItem = GetBool(BlackBoard, "bIsValidItem")
    
    local Visibility = (bIsValidItem and self.ShowPriceArray:Contains(TipsId)) and UE.ESlateVisibility.SelfHitTestInvisible or UE.ESlateVisibility.Collapsed
    print("ES_EnhanceExtractionTips:UpdateData EnhanceState",EnhanceState,"Visibility",Visibility,"TipsId",TipsId)
    local EnhanceAttributeArrayStr = GetString(BlackBoard, "EnhanceAttributeArray")
    local EnhanceAttributeArray = UE.UKismetStringLibrary.ParseIntoArray(EnhanceAttributeArrayStr, ",", true)
    local Num = EnhanceAttributeArray:Length()

    --剩余强化次数
    local RemainingCount = GetInt(BlackBoard, "RemainingCount")
    local RemainWarninVisible = (TipsId == UE.EEnhanceTips.EnhanceTimesOut) and UE.ESlateVisibility.SelfHitTestInvisible or UE.ESlateVisibility.Collapsed
    local RemainTextColor = (TipsId == UE.EEnhanceTips.EnhanceTimesOut) and self.RemainTextWarningColor or self.RemainTextNormalColor
    local RemainImgColor = (TipsId == UE.EEnhanceTips.EnhanceTimesOut) and self.RemainImgWarningColor or self.RemainImgNormalColor
    self.GUIImage_Line:SetVisibility(RemainWarninVisible)
    self.GUIImage_Line:SetColorAndOpacity(RemainImgColor)
    self.TextBlock_ItemType:SetColorAndOpacity(RemainTextColor)
    self.TextBlock_ItemType:SetText(StringUtil.Format(G_ConfigHelper:GetStrFromCommonStaticST("Lua_ES_remaining"),RemainingCount))

    self.GameState = UE.UGameplayStatics.GetGameState(self)

    --region 时间更新
    self.ResetTimeStamp =  GetFloat(BlackBoard, "ResetTimeStamp")

    if self.ResetTimerHandle ~= nil then
        UE.UKismetSystemLibrary.K2_ClearTimerHandle(self, self.ResetTimerHandle)
        self.ResetTimerHandle = nil
    end

    self.ResetTimerHandle = UE.UKismetSystemLibrary.K2_SetTimerDelegate({self, self.UpdateTime}, 1, true, 0, 0)
    --endregion


    --强化类型
    local EnhanceType = GetEnum(BlackBoard, "EnhanceType")

    --当前武器状态
    local bIsCurrentWeaponCanAttach = GetBool(BlackBoard, "bIsCurrentWeaponCanAttach")
    -- 未装备武器可强化
    local bIsUnEquippedWeaponCanAttach = GetBool(BlackBoard, "bIsUnEquippedWeaponCanAttach")

    local LocalPC = UE.UGameplayStatics.GetPlayerController(self, 0)
    local BagComponent = UE.UBagComponent.Get(LocalPC)
    if EnhanceType == UE.EEnhancementStationType.Weapon then
        --如果是武器


        self.Content:SetActiveWidgetIndex(0)

        local Data = UE.UEnhancementSettings.GetAttributeDataById(Owner, EnhanceAttributeArray[1])
        self.TextBlock_ItemName:SetText(Data.EnhanceName) -- 词条名称
        self.TextBlock_DetailDescribe:SetText(Data.EnhanceDecription) -- 词条描述
        -- self.Image_BG:SetBrushFromSoftTexture(UE.UGFUnluaHelper.ToSoftObjectPtr(Data.EnhanceBg), true) -- 词条背景
        self.Image_Item:SetBrushFromSoftTexture(UE.UGFUnluaHelper.ToSoftObjectPtr(Data.EnhanceIcon), true) -- 词条图标

        if bIsCurrentWeaponCanAttach then

            
            --可以强化
            self:AddActiveWidgetStyleFlags(9)
            --self.WS_WeaponEnhanceState:SetActiveWidgetIndex(0)
            local HoldWeaponInstance = GetObject(BlackBoard,"ItemObject")

            if HoldWeaponInstance then
                local WeaponIndentity = HoldWeaponInstance:GetInventoryIdentity()
                local WeaponSlot,bIsFind = BagComponent:GetItemSlot(WeaponIndentity)
                if bIsFind then
                    local WeaponSlotID = WeaponSlot.SlotID

                    local HandWeaponIndexImage = WeaponSlotID == 1 and self.WeaponSlotIndex0 or self.WeaponSlotIndex1
                    local UnhandWeaponIndexImage = WeaponSlotID == 1 and self.WeaponSlotIndex1 or  self.WeaponSlotIndex0
                    HandWeaponIndexImage:SetColorAndOpacity(self.HandWeaponColor)
                    UnhandWeaponIndexImage:SetColorAndOpacity(self.UnhandWeaponColor)

                   -- self.TextSlotID:SetText(tostring(WeaponSlotID))

                    local WeaponIcon, IsExistWeaponIcon = UE.UItemSystemManager.GetItemDataFString(self, 
                    WeaponIndentity.ItemID, "FlowImage", GameDefine.NItemSubTable.Ingame,"ES_EnhanceExtractionTips:UpdateData")
                    if IsExistWeaponIcon then
                        local ImageSoftObjectPtr = UE.UGFUnluaHelper.ToSoftObjectPtr(WeaponIcon)
                        self.ImageSupportWeapon:SetBrushFromSoftTexture(ImageSoftObjectPtr)
                    end

                    local WeaponName, IsExistWeaponName = UE.UItemSystemManager.GetItemDataFText(self, 
                    WeaponIndentity.ItemID, "ItemName", GameDefine.NItemSubTable.Ingame,"ES_EnhanceExtractionTips:UpdateData")
                    if IsExistWeaponName then
                        self.Text_SupportWeapon:SetText(StringUtil.Format(WeaponName))
                    end
                end
            end

        elseif bIsUnEquippedWeaponCanAttach then
            -- 未装备武器可强化
            self:AddActiveWidgetStyleFlags(4)
            local UnholdWeaponInstance = GetObject(BlackBoard,"OtherItemObject")
            if UnholdWeaponInstance then
                if UnholdWeaponInstance then
                    local WeaponIndentity = UnholdWeaponInstance:GetInventoryIdentity()
                    local WeaponSlot,bIsFind = BagComponent:GetItemSlot(WeaponIndentity)
                    if bIsFind then
                        local WeaponSlotID = WeaponSlot.SlotID
                        self.TextSlotID:SetText(tostring(WeaponSlotID))

                        local WeaponIcon, IsExistWeaponIcon = UE.UItemSystemManager.GetItemDataFString(self, 
                        WeaponIndentity.ItemID, "FlowImage", GameDefine.NItemSubTable.Ingame,"SimpleReadyPickListUI:HandlPickItemState")
                        if IsExistWeaponIcon then
                            local ImageSoftObjectPtr = UE.UGFUnluaHelper.ToSoftObjectPtr(WeaponIcon)
                            self.Imag_WeaponIcon:SetBrushFromSoftTexture(ImageSoftObjectPtr)
                        end

                        local WeaponName, IsExistWeaponName = UE.UItemSystemManager.GetItemDataFText(self, 
                        WeaponIndentity.ItemID, "ItemName", GameDefine.NItemSubTable.Ingame,"SimpleReadyPickListUI:HandlPickItemState")
                        if IsExistWeaponName then
                            self.Text_WeaponName:SetText(StringUtil.Format(WeaponName))
                        end
                        
                    end
                end
            end


            --self.WS_WeaponEnhanceState:SetActiveWidgetIndex(1)
        else
            --武器类型不匹配


            self:AddActiveWidgetStyleFlags(2)

            local EffectId = tonumber(Data.EnhanceRefKey)
            local WeaponTags = UE.UGAWAttachmentFunctionLibrary.GetAvailableWeaponTagsByEffectId(Owner, EffectId)
            local WeaponTagNum = WeaponTags:Num()

            local NameItems = self.UnmatchWeaponState:GetAllChildren()
            local NameItemNum = NameItems:Num()

            for i = 1, NameItemNum do
                if i <= WeaponTagNum then
                    NameItems[i].WeaponName:SetText(UE.UBlueprintGameplayTagLibrary.GetTagName(WeaponTags[i]))

                    for TagIndex = 1, self.WeaponTagList:Num() do
                        if self.WeaponTagList[TagIndex] == WeaponTags[i] then
                            NameItems[i].WeaponName:SetText(self.WeaponNameList[TagIndex])
                        end
                    end

                    NameItems[i]:SetVisibility(UE.ESlateVisibility.Visible)
                else
                    NameItems[i]:SetVisibility(UE.ESlateVisibility.Collapsed)
                end
            end
            --self.WS_WeaponEnhanceState:SetActiveWidgetIndex(2)
        end



    else
        --装备

        --根据EnhanceType强化类型设置Icon样式
        local EquipSoftTex2D = self.EquipIconMap:Find(EnhanceType)
        if EquipSoftTex2D then
            self.Image_Item:SetBrushFromSoftTexture(EquipSoftTex2D,false)
        end
        
        local EquipmentLv = -1
        local QueryEquipType = nil
        if EnhanceType == UE.EEnhancementStationType.ArmorHead then
            QueryEquipType = ItemSystemHelper.NItemType.ArmorHead
        elseif EnhanceType == UE.EEnhancementStationType.ArmorBody then
            QueryEquipType = ItemSystemHelper.NItemType.ArmorBody
        elseif EnhanceType == UE.EEnhancementStationType.Bag then
            QueryEquipType = ItemSystemHelper.NItemType.Bag
        end

        self.Image_Quality:SetVisibility(UE.ESlateVisibility.Collapsed)
        if QueryEquipType then
            EquipmentLv = self:QueryEuipmentLevel(QueryEquipType)
            if  EquipmentLv > 0 then
                local BgTex2D = self.EquipmentLvBgArr:Get(EquipmentLv)
                if BgTex2D then
                    self.Image_Quality:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
                    self.Image_Quality:SetBrushFromSoftTexture(BgTex2D,false)
                end
            end
        end



        if TipsId == UE.EEnhanceTips.InvalidItem then
            -- InvalidItem 没有可强化道具
            self:AddActiveWidgetStyleFlags(6)
        elseif TipsId == UE.EEnhanceTips.NoCurrency then
            -- NoCurrency 货币不足
            self:AddActiveWidgetStyleFlags(5)
        elseif TipsId == UE.EEnhanceTips.EnhanceTimesOut then
            -- EnhanceTimesOut 强化次数用尽
            self:AddActiveWidgetStyleFlags(8)
        elseif TipsId == UE.EEnhanceTips.CanEnhance then
            -- CanEnhance 可以强化
            self:AddActiveWidgetStyleFlags(5)
        end

        self:AddActiveWidgetStyleFlags(5)
        self.Content:SetActiveWidgetIndex(1)
        self.TextBlock_ItemName:SetText(StringUtil.Format(G_ConfigHelper:GetStrFromCommonStaticST("Lua_ES_random"))) -- 词条名称
        for i = 1, Num do
            local Data = UE.UEnhancementSettings.GetAttributeDataById(Owner, EnhanceAttributeArray[i])

            self["TextBlock_AttributeName_"..i]:SetText(Data.EnhanceName) -- 词条名称
            --self["TextBlock_DetailDescribe_"..i]:SetText(Data.EnhanceDecription) -- 词条描述
            self["Image_AttributeIcon_"..i]:SetBrushFromSoftTexture(UE.UGFUnluaHelper.ToSoftObjectPtr(Data.EnhanceIcon), false) -- 词条图标
        end

    end

end


function ES_EnhanceExtractionTips:UpdateTime()
    local CurrentTimeStamp = self.GameState:GetServerWorldTimeSeconds()
    local EndTime = self.ResetTimeStamp - CurrentTimeStamp
    if EndTime < 0 then
        UE.UKismetSystemLibrary.K2_ClearTimerHandle(self, self.ResetTimerHandle)
        self.Text_TimeTip:SetVisibility(UE.ESlateVisibility.Collapsed)
    else
        self.Text_TimeTip:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
    end
    local EndTimeInt = math.ceil(EndTime)
    local UpdateStr = StringUtil.Format(G_ConfigHelper:GetStrFromCommonStaticST("Lua_ES_Refreshthecontentatt"),TimeUtils.getTimeStringSimple(math.ceil(EndTimeInt)))
    --剩余刷新时间
    self.Text_TimeTip:SetText(UpdateStr)
end


function ES_EnhanceExtractionTips:OnDestroy()
    UE.UKismetSystemLibrary.K2_ClearTimerHandle(self, self.ResetTimerHandle)
end


function ES_EnhanceExtractionTips:OnMobileTipButtonClicked()
    print("ES_EnhanceExtractionTips >> OnMobileTipButtonClicked", GetObjectName(self))
end

function ES_EnhanceExtractionTips:OnStrengthenButtonClicked()
    print("ES_EnhanceExtractionTips >> OnStrengthenButtonClicked", GetObjectName(self))
    if self.RootOverlay then
        self.RootOverlay:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
    end

    if self.BP_MobileTipButton then
        self.BP_MobileTipButton:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
    end

    if self.StrengthenButton then
        self.StrengthenButton:SetVisibility(UE.ESlateVisibility.Collapsed)
    end
end

function ES_EnhanceExtractionTips:QueryEuipmentLevel(InItemType)
    local LocalPC = UE.UGameplayStatics.GetPlayerController(self, 0)
    local BagComponent = UE.UBagComponent.Get(LocalPC)
    local SortedInventoryInstanceArray = BagComponent:GetSortedInventoryElements()
    local InventoryInstanceNum = SortedInventoryInstanceArray:Length()

    local RealIndex = 0
    for index = 1, InventoryInstanceNum, 1 do
        local TempInventoryInstance = SortedInventoryInstanceArray:Get(index)
        if not TempInventoryInstance then
            goto continue
        end

        local CurrentInventoryInstanceNum = TempInventoryInstance:GetStackNum()
        if CurrentInventoryInstanceNum <= 0 then
            goto continue
        end

        if TempInventoryInstance:GetIsHasRemoveFlag() then
            goto continue
        end

        local ItemID = TempInventoryInstance:GetInventoryIdentity().ItemID
        local CurrentItemType, RetItemType = UE.UItemSystemManager.GetItemDataFName(BagComponent, ItemID , "ItemType", GameDefine.NItemSubTable.Ingame, "UIQuickPickBase:RefreshSlot")

        if not RetItemType then
            print("Error: ES_EnhanceExtractionTips:QueryEuipmentLevel ItemType can't find. ItemId = ", tostring(TempInventoryInstance:GetInventoryIdentity().ItemID))
            goto continue
        end

        --ItemSystemHelper.NItemType.ArmorHead
        if CurrentItemType == InItemType then
            local CurrentItemLv, RetItemLv = UE.UItemSystemManager.GetItemDataUInt8(BagComponent, ItemID , "ItemLevel", GameDefine.NItemSubTable.Ingame, "UIQuickPickBase:RefreshSlot")
            if RetItemLv then
                return CurrentItemLv
            end
 
        end
        ::continue::
    end

    return -1
end

return ES_EnhanceExtractionTips