---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2023/9/25 15:30
---
---
local ES_InfoPanel = Class("Common.Framework.UserWidget")

local function GetInt(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsIntSimple(BlackBoard,Key)
    return Value
end

local function GetName(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsNameSimple(BlackBoard,Key)
    return Value
end

local function GetString(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsStringSimple(BlackBoard,Key)
    return Value
end

local function GetEnum(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsEnumSimple(BlackBoard,Key)
    return Value
end

local function GetFloat(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsFloatSimple(BlackBoard,Key)
    return Value
end

local function GetBool(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsBoolSimple(BlackBoard,Key)
    return Value
end

local function GetObject(BlackBoard, Key)
    local Value,Result =UE.UGenericBlackboardBlueprintFunctionLibrary.TryGetValueAsObjectSimple(BlackBoard,Key)
    return Value
end


function ES_InfoPanel:OnInit()

    if BridgeHelper.IsMobilePlatform() then
        if self.RootOverlay then
            self.RootOverlay:SetVisibility(UE.ESlateVisibility.Collapsed)
        end
        if self.BP_MobileTipButton then
            self.BP_MobileTipButton:SetVisibility(UE.ESlateVisibility.Collapsed)
        end

        if self.StrengthenButton then
            self.StrengthenButton:SetVisibility(UE.ESlateVisibility.Visible)
            self.BindNodes = {
                { UDelegate = self.StrengthenButton.OnClicked,				Func = self.OnStrengthenButtonClicked},
                --{ UDelegate = self.BP_MobileTipButton.OnClicked,				Func = self.OnMobileTipButtonClicked},
            }
        end
    end

	UserWidget.OnInit(self)
end

function ES_InfoPanel:OnShow(InContext, InGenericBlackboard)
end



function ES_InfoPanel:UpdateData(Owner, Count, BlackBoard)

    local EnhanceState = GetInt(BlackBoard, "EnhanceState")
    self.WS_EnhanceState:SetActiveWidgetIndex(EnhanceState < 3 and EnhanceState or 0)

    if EnhanceState == 0 or EnhanceState == 3 then
        --等待强化阶段UI
        self:WaitEnhanceState(Owner, Count, BlackBoard)
    elseif EnhanceState == 1 then
        --强化中阶段UI
        self:EnhancingState(Owner, Count, BlackBoard)
    elseif EnhanceState == 2 then
        --等待拾取阶段UI
        self:WaitFetchState(Owner, Count, BlackBoard)
    end

end


function ES_InfoPanel:UpdateTime()
    local CurrentTimeStamp = self.GameState:GetServerWorldTimeSeconds()
    local EndTime = self.ResetTimeStamp - CurrentTimeStamp
    if EndTime < 0 then
        UE.UKismetSystemLibrary.K2_ClearTimerHandle(self, self.ResetTimerHandle)
        self.Text_TimeTip:SetVisibility(UE.ESlateVisibility.Collapsed)
    else
        self.Text_TimeTip:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
    end
    local EndTimeInt = math.ceil(EndTime)
    local UpdateStr = StringUtil.Format(G_ConfigHelper:GetStrFromCommonStaticST("Lua_ES_Refreshthecontentatt"),TimeUtils.getTimeStringSimple(math.ceil(EndTimeInt)))
    --剩余刷新时间
    self.Text_TimeTip:SetText(UpdateStr)
end


function ES_InfoPanel:OnDestroy()
    UE.UKismetSystemLibrary.K2_ClearTimerHandle(self, self.ResetTimerHandle)
    UE.UKismetSystemLibrary.K2_ClearTimerHandle(self, self.EnhanceTimerHandle)
end


function ES_InfoPanel:OnMobileTipButtonClicked()
    print("ES_InfoPanel >> OnMobileTipButtonClicked", GetObjectName(self))
end

function ES_InfoPanel:OnStrengthenButtonClicked()
    print("ES_InfoPanel >> OnStrengthenButtonClicked", GetObjectName(self))
    if self.RootOverlay then
        self.RootOverlay:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
    end

    if self.BP_MobileTipButton then
        self.BP_MobileTipButton:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
    end

    if self.StrengthenButton then
        self.StrengthenButton:SetVisibility(UE.ESlateVisibility.Collapsed)
    end
end


function ES_InfoPanel:QueryEuipmentLevel(InItemObject)
    local LocalPC = UE.UGameplayStatics.GetPlayerController(self, 0)
    local BagComponent = UE.UBagComponent.Get(LocalPC)
    local InventoryIdentity = InItemObject:GetInventoryIdentity()
    local CurrentItemLv, RetItemLv = UE.UItemSystemManager.GetItemDataUInt8(BagComponent, InventoryIdentity.ItemID , "ItemLevel", GameDefine.NItemSubTable.Ingame, "UIQuickPickBase:RefreshSlot")
    if RetItemLv then
        return CurrentItemLv
    end
    return -1
end

function ES_InfoPanel:QueryEuipmentLevelByID(ItemID)
    local LocalPC = UE.UGameplayStatics.GetPlayerController(self, 0)
    local BagComponent = UE.UBagComponent.Get(LocalPC)
    local CurrentItemLv, RetItemLv = UE.UItemSystemManager.GetItemDataUInt8(BagComponent, ItemID, "ItemLevel", GameDefine.NItemSubTable.Ingame, "UIQuickPickBase:RefreshSlot")
    if RetItemLv then
        return CurrentItemLv
    end
    return -1
end

function ES_InfoPanel:WaitEnhanceState(Owner, Count, BlackBoard)

    self:RemoveAllActiveWidgetStyleFlags()

    local bEnable = GetBool(BlackBoard, "EnableInteractive")
    local ItemObject = GetObject(BlackBoard, "ItemObject")
    local EnhanceState = GetInt(BlackBoard, "EnhanceState")
    self.BP_TitleTips.InputHint:SetVisibility(bEnable and UE.ESlateVisibility.Visible or UE.ESlateVisibility.Collapsed)
    self.TextBlock_Price:SetVisibility(EnhanceState == UE.EEnhanceTips.EnhanceTimesOut and UE.ESlateVisibility.Collapsed or UE.ESlateVisibility.SelfHitTestInvisible)
    local TipsId = GetEnum(BlackBoard, "TipsMessage")

    local Message = self.TipsContentList[TipsId]
    local TipsColor = self.TipsColorList[TipsId]

    --交互提示
    self.BP_TitleTips.Text_Making:SetText(Message)
    self.BP_TitleTips.Text_Making:SetColorAndOpacity(TipsColor)


    local Price = GetInt(BlackBoard, "EnhancePrice")
    if Price <= 0 then
        Price = GetInt(BlackBoard, "CurrentEnhancePrice")
    end
    --价格
    self.TextBlock_Price:SetText(Price)
    --是不是有效的物品
    local bIsValidItem = GetBool(BlackBoard, "bIsValidItem")
    
    local Visibility = (bIsValidItem and self.ShowPriceArray:Contains(TipsId)) and UE.ESlateVisibility.SelfHitTestInvisible or UE.ESlateVisibility.Collapsed
    print("ES_InfoPanel:UpdateData EnhanceState",EnhanceState,"Visibility",Visibility,"TipsId",TipsId)
    local EnhanceAttributeArrayStr = GetString(BlackBoard, "EnhanceAttributeArray")
    local EnhanceAttributeArray = UE.UKismetStringLibrary.ParseIntoArray(EnhanceAttributeArrayStr, ",", true)
    local Num = EnhanceAttributeArray:Length()

    --剩余强化次数
    local RemainingCount = GetInt(BlackBoard, "RemainingCount")
    local RemainWarninVisible = (TipsId == UE.EEnhanceTips.EnhanceTimesOut) and UE.ESlateVisibility.SelfHitTestInvisible or UE.ESlateVisibility.Collapsed
    local RemainTextColor = (TipsId == UE.EEnhanceTips.EnhanceTimesOut) and self.RemainTextWarningColor or self.RemainTextNormalColor
    local RemainImgColor = (TipsId == UE.EEnhanceTips.EnhanceTimesOut) and self.RemainImgWarningColor or self.RemainImgNormalColor
    self.GUIImage_Line:SetVisibility(RemainWarninVisible)
    self.GUIImage_Line:SetColorAndOpacity(RemainImgColor)
    self.TextBlock_ItemType:SetColorAndOpacity(RemainTextColor)
    self.TextBlock_ItemType:SetText(StringUtil.Format(G_ConfigHelper:GetStrFromCommonStaticST("Lua_ES_remaining"),RemainingCount))

    self.GameState = UE.UGameplayStatics.GetGameState(self)

    --region 时间更新
    self.ResetTimeStamp =  GetFloat(BlackBoard, "ResetTimeStamp")

    if self.ResetTimerHandle ~= nil then
        UE.UKismetSystemLibrary.K2_ClearTimerHandle(self, self.ResetTimerHandle)
        self.ResetTimerHandle = nil
    end

    self.ResetTimerHandle = UE.UKismetSystemLibrary.K2_SetTimerDelegate({self, self.UpdateTime}, 1, true, 0, 0)
    --endregion


    --强化类型
    local EnhanceType = GetEnum(BlackBoard, "EnhanceType")

    --当前武器状态
    local bIsCurrentWeaponCanAttach = GetBool(BlackBoard, "bIsCurrentWeaponCanAttach")
    -- 未装备武器可强化
    local bIsUnEquippedWeaponCanAttach = GetBool(BlackBoard, "bIsUnEquippedWeaponCanAttach")

    local LocalPC = UE.UGameplayStatics.GetPlayerController(self, 0)
    local BagComponent = UE.UBagComponent.Get(LocalPC)
    if EnhanceType == UE.EEnhancementStationType.Weapon then
        --如果是武器
        self.Content:SetActiveWidgetIndex(0)

        local Data = UE.UEnhancementSettings.GetAttributeDataById(Owner, EnhanceAttributeArray[1])
        self.TextBlock_ItemName:SetText(Data.EnhanceName) -- 词条名称
        self.TextBlock_DetailDescribe:SetText(Data.EnhanceDecription) -- 词条描述
        self.Image_Item:SetBrushFromSoftTexture(UE.UGFUnluaHelper.ToSoftObjectPtr(Data.EnhanceIcon), true) -- 词条图标

        if bIsCurrentWeaponCanAttach then
            --可以强化
            self:AddActiveWidgetStyleFlags(9)
            self:EnhanceableWeapon(BlackBoard,BagComponent,self.WeaponSlotIndex0,self.WeaponSlotIndex1,self.ImageSupportWeapon,self.Text_SupportWeapon)

        elseif bIsUnEquippedWeaponCanAttach then
            -- 未装备武器可强化
            self:AddActiveWidgetStyleFlags(4)
            self:UnhandWeaponButEnhanced(BlackBoard,BagComponent,self.TextSlotID,self.Imag_WeaponIcon,self.Text_WeaponName)
        else
            --武器类型不匹配
            self:AddActiveWidgetStyleFlags(2)
            self:UnmatchWeaponStyle(Owner,Data,self.UnmatchWeaponState)
        end
    else
        --装备

        --根据EnhanceType强化类型设置Icon样式
        local EquipSoftTex2D = self.EquipIconMap:Find(EnhanceType)
        if EquipSoftTex2D then
            self.Image_Item:SetBrushFromSoftTexture(EquipSoftTex2D,false)
        end
    

        self.Image_Quality:SetVisibility(UE.ESlateVisibility.Collapsed)

        if ItemObject then
            local EquipmentLv = self:QueryEuipmentLevel(ItemObject)
            if  EquipmentLv > 0 then
                local BgTex2D = self.EquipmentLvBgArr:Get(EquipmentLv)
                if BgTex2D then
                    self.Image_Quality:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
                    self.Image_Quality:SetBrushFromSoftTexture(BgTex2D,false)
                end
            end
        end




        if TipsId == UE.EEnhanceTips.InvalidItem then
            -- InvalidItem 没有可强化道具
            self:AddActiveWidgetStyleFlags(6)
        elseif TipsId == UE.EEnhanceTips.NoCurrency then
            -- NoCurrency 货币不足
            self:AddActiveWidgetStyleFlags(5)
        elseif TipsId == UE.EEnhanceTips.EnhanceTimesOut then
            -- EnhanceTimesOut 强化次数用尽
            self:AddActiveWidgetStyleFlags(8)
        elseif TipsId == UE.EEnhanceTips.CanEnhance then
            -- CanEnhance 可以强化
            self:AddActiveWidgetStyleFlags(5)
        end

        self:AddActiveWidgetStyleFlags(5)
        self.Content:SetActiveWidgetIndex(1)
        self.TextBlock_ItemName:SetText(StringUtil.Format(G_ConfigHelper:GetStrFromCommonStaticST("Lua_ES_random"))) -- 词条名称
        for i = 1, Num do
            local Data = UE.UEnhancementSettings.GetAttributeDataById(Owner, EnhanceAttributeArray[i])

            self["TextBlock_AttributeName_"..i]:SetText(Data.EnhanceName) -- 词条名称
            --self["TextBlock_DetailDescribe_"..i]:SetText(Data.EnhanceDecription) -- 词条描述
            self["Image_AttributeIcon_"..i]:SetBrushFromSoftTexture(UE.UGFUnluaHelper.ToSoftObjectPtr(Data.EnhanceIcon), false) -- 词条图标
        end

    end
end

--强化中
function ES_InfoPanel:EnhancingState(Owner, Count, BlackBoard)

    --准备数据
    local TipsId = GetEnum(BlackBoard, "TipsMessage")
    local EnhanceType = GetEnum(BlackBoard, "EnhanceType")
    local EnhanceAttributeId = GetString(BlackBoard, "EnhanceAttributeId")
    local ItemObject = GetObject(BlackBoard, "ItemObject")
    local StationActor = GetObject(BlackBoard, "StationActor")
    -- 交互提示
    local Message = self.TipsContentList[7]
    self.Text_Making:SetText(Message)


    --根据不同类型设置样式
    if EnhanceType == UE.EEnhancementStationType.Weapon then
        self.Image_EnhancingBG:SetVisibility(UE.ESlateVisibility.Collapsed)
        self.Image_IconDesc:SetVisibility(UE.ESlateVisibility.Collapsed)

        local EnhanceAttribute = UE.UEnhancementSettings.GetAttributeDataById(Owner,EnhanceAttributeId)
        self.Image_EnhancingIcon:SetBrushFromSoftTexture(UE.UGFUnluaHelper.ToSoftObjectPtr(EnhanceAttribute.EnhanceIcon), true) -- 词条图标

    else
        self.Image_IconDesc:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
        
        local EquipSoftTex2D = self.EquipIconMap:Find(EnhanceType)
        if EquipSoftTex2D then
            self.Image_EnhancingIcon:SetBrushFromSoftTexture(EquipSoftTex2D, false)
        end

        self.Image_EnhancingBG:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
        if ItemObject then
            local EquipmentLv = self:QueryEuipmentLevel(ItemObject)
            if EquipmentLv > 0 then
                local BgTex2D = self.FetchEquipmentLvBgArr:Get(EquipmentLv)
                if BgTex2D then
                    self.Image_EnhancingBG:SetBrushFromSoftTexture(BgTex2D, false)
                end
            end
        end

    end

    print("ES_InfoPanel >> UpdateProgressBar > K2_SetTimerDelegate")
    self.EnhanceRemainTimer = StationActor:GetLocalRemainTimer()
    self.EnhanceTimerHandle = UE.UKismetSystemLibrary.K2_SetTimerDelegate({self, self.UpdateProgressBar}, 0.1, true, 0, 0)
    

end

-- function ES_InfoPanel:Tick()

-- end


function ES_InfoPanel:UpdateProgressBar()
    self.EnhanceRemainTimer = self.EnhanceRemainTimer - 0.1
    if self.EnhanceRemainTimer < 0 then
        self.EnhanceRemainTimer = 0
        UE.UKismetSystemLibrary.K2_ClearTimerHandle(self, self.EnhanceTimerHandle)
    end
    local RrogRote = self.EnhanceRemainTimer / 5.0
    self.Prog_Remain:SetPercent(RrogRote)
    local ProgStr = string.format("%.1fs", self.EnhanceRemainTimer)
    self.Text_RemainTime:SetText(ProgStr)

    print("ES_InfoPanel >> UpdateProgressBar > GetObjectName=",GetObjectName(self),"ProgStr=",ProgStr)
end


--等待拾取状态
function ES_InfoPanel:WaitFetchState(Owner, Count, BlackBoard)

    --交互提示
    local TipsId = GetEnum(BlackBoard, "TipsMessage")
    local bEnable = GetBool(BlackBoard, "EnableInteractive")
    local Message = self.TipsContentList[TipsId]
    local TipsColor = self.TipsColorList[TipsId]
    self.BP_WaitFetchTitleTips.Text_Making:SetText(Message)
    self.BP_WaitFetchTitleTips.Text_Making:SetColorAndOpacity(TipsColor)
    self.BP_WaitFetchTitleTips.InputHint:SetVisibility(bEnable and UE.ESlateVisibility.Visible or UE.ESlateVisibility.Collapsed)

    local EnhanceAttributeId = GetString(BlackBoard, "EnhanceAttributeId")
    local Data = UE.UEnhancementSettings.GetAttributeDataById(Owner,EnhanceAttributeId)
    --强化类型
    local EnhanceType = GetEnum(BlackBoard, "EnhanceType")
    local EnhancedItemId = GetInt(BlackBoard, "EnhancedItemId")
    if EnhancedItemId then

        local WeaponIcon, IsExistWeaponIcon = UE.UItemSystemManager.GetItemDataFString(self,
        EnhancedItemId, "ItemIcon", GameDefine.NItemSubTable.Ingame,
        "SimpleReadyPickListUI:HandlPickItemState")
        if IsExistWeaponIcon then
            local ImageSoftObjectPtr = UE.UGFUnluaHelper.ToSoftObjectPtr(WeaponIcon)
            self.FetchImage_Bg_Item:SetBrushFromSoftTexture(ImageSoftObjectPtr)
        end
        
        local ItemName, IsExistItemName = UE.UItemSystemManager.GetItemDataFText(self,
        EnhancedItemId, "ItemName", GameDefine.NItemSubTable.Ingame,
        "SimpleReadyPickListUI:HandlPickItemState")
        if IsExistItemName then
            self.FetchItemName:SetText(StringUtil.Format(ItemName))
        end
    end
    
    self.EnhanceName:SetText(Data.EnhanceName) -- 词条名称
    local LocalPC = UE.UGameplayStatics.GetPlayerController(self, 0)
    local BagComponent = UE.UBagComponent.Get(LocalPC)
    self.FetchWeaponPanel:SetVisibility((EnhanceType == UE.EEnhancementStationType.Weapon) and UE.ESlateVisibility.SelfHitTestInvisible or UE.ESlateVisibility.Collapsed)
    if EnhanceType == UE.EEnhancementStationType.Weapon then
        --武器

        self.Image_FetchRandom:SetVisibility(UE.ESlateVisibility.Collapsed)
        self.FetchImage_Quality:SetVisibility(UE.ESlateVisibility.Collapsed)

        self.FetchImage_Item:SetBrushFromSoftTexture(UE.UGFUnluaHelper.ToSoftObjectPtr(Data.EnhanceIcon), true) -- 词条图标

        --当前武器状态
        local bIsCurrentWeaponCanAttach = GetBool(BlackBoard, "bIsCurrentWeaponCanAttach")
        -- 未装备武器可强化
        local bIsUnEquippedWeaponCanAttach = GetBool(BlackBoard, "bIsUnEquippedWeaponCanAttach")


        if bIsCurrentWeaponCanAttach then
            --可以强化
            self.WS_FetchHandWeaponState:SetActiveWidgetIndex(0)
            self:EnhanceableWeapon(BlackBoard,BagComponent,self.FetchWeaponSlotIndex0,self.FetchWeaponSlotIndex1,self.ImageSupportWeapon_1,self.Text_SupportWeapon_1)

        elseif bIsUnEquippedWeaponCanAttach then
            -- 未装备武器可强化
            self.WS_FetchHandWeaponState:SetActiveWidgetIndex(1)
            self:UnhandWeaponButEnhanced(BlackBoard,BagComponent,self.FetchTextSlotID,self.FetchImag_WeaponIcon,self.FetchText_SupportWeapon)
        else
            --武器类型不匹配
            self.WS_FetchHandWeaponState:SetActiveWidgetIndex(2)
            self:UnmatchWeaponStyle(Owner,Data,self.FetchUnmatchWeaponState)
        end

    else
        --装备
        -- 根据EnhanceType强化类型设置Icon样式
        local EquipSoftTex2D = self.EquipIconMap:Find(EnhanceType)
        if EquipSoftTex2D then
            self.FetchImage_Item:SetBrushFromSoftTexture(EquipSoftTex2D, false)
        end

        self.Image_FetchRandom:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
        self.FetchImage_Quality:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)

        if EnhancedItemId then
            local EquipmentLv = self:QueryEuipmentLevelByID(EnhancedItemId)
            if EquipmentLv > 0 then
                local BgTex2D = self.FetchEquipmentLvBgArr:Get(EquipmentLv)
                if BgTex2D then
                    self.FetchImage_Quality:SetVisibility(UE.ESlateVisibility.SelfHitTestInvisible)
                    self.FetchImage_Quality:SetBrushFromSoftTexture(BgTex2D, false)
                end
            end
        end

    end
end


--没有匹配的武器
function ES_InfoPanel:UnmatchWeaponStyle(Owner,Data,WrapBox)
    local EffectId = tonumber(Data.EnhanceRefKey)
    local WeaponTags = UE.UGAWAttachmentFunctionLibrary.GetAvailableWeaponTagsByEffectId(Owner, EffectId)
    local WeaponTagNum = WeaponTags:Num()

    local NameItems = WrapBox:GetAllChildren()
    local NameItemNum = NameItems:Num()

    for i = 1, NameItemNum do
        if i <= WeaponTagNum then
            NameItems[i].WeaponName:SetText(UE.UBlueprintGameplayTagLibrary.GetTagName(WeaponTags[i]))

            for TagIndex = 1, self.WeaponTagList:Num() do
                if self.WeaponTagList[TagIndex] == WeaponTags[i] then
                    NameItems[i].WeaponName:SetText(self.WeaponNameList[TagIndex])
                end
            end

            NameItems[i]:SetVisibility(UE.ESlateVisibility.Visible)
        else
            NameItems[i]:SetVisibility(UE.ESlateVisibility.Collapsed)
        end
    end
end

-- 未手持武器，但可强化
function ES_InfoPanel:UnhandWeaponButEnhanced(BlackBoard,BagComponent,TextSlotID,ImgWeaponIcon,TextWeaponName)
    -- 未装备武器可强化
    local UnholdWeaponInstance = GetObject(BlackBoard, "OtherItemObject")
    if UnholdWeaponInstance then
        if UnholdWeaponInstance then
            local WeaponIndentity = UnholdWeaponInstance:GetInventoryIdentity()
            local WeaponSlot, bIsFind = BagComponent:GetItemSlot(WeaponIndentity)
            if bIsFind then
                local WeaponSlotID = WeaponSlot.SlotID
                TextSlotID:SetText(tostring(WeaponSlotID))

                local WeaponIcon, IsExistWeaponIcon = UE.UItemSystemManager.GetItemDataFString(self,
                    WeaponIndentity.ItemID, "FlowImage", GameDefine.NItemSubTable.Ingame,
                    "SimpleReadyPickListUI:HandlPickItemState")
                if IsExistWeaponIcon then
                    local ImageSoftObjectPtr = UE.UGFUnluaHelper.ToSoftObjectPtr(WeaponIcon)
                    ImgWeaponIcon:SetBrushFromSoftTexture(ImageSoftObjectPtr)
                end

                local WeaponName, IsExistWeaponName = UE.UItemSystemManager.GetItemDataFText(self,
                    WeaponIndentity.ItemID, "ItemName", GameDefine.NItemSubTable.Ingame,
                    "SimpleReadyPickListUI:HandlPickItemState")
                if IsExistWeaponName then
                    TextWeaponName:SetText(StringUtil.Format(WeaponName))
                end

            end
        end
    end
end

function ES_InfoPanel:EnhanceableWeapon(BlackBoard,BagComponent,ImgSlot1,ImgSlot2,ImgWeaponIcon,TextWeaponName)
    local HoldWeaponInstance = GetObject(BlackBoard,"ItemObject")

    if HoldWeaponInstance then
        local WeaponIndentity = HoldWeaponInstance:GetInventoryIdentity()
        local WeaponSlot,bIsFind = BagComponent:GetItemSlot(WeaponIndentity)
        if bIsFind then
            local WeaponSlotID = WeaponSlot.SlotID

            local HandWeaponIndexImage = WeaponSlotID == 1 and ImgSlot1 or ImgSlot2
            local UnhandWeaponIndexImage = WeaponSlotID == 1 and ImgSlot2 or  ImgSlot1
            HandWeaponIndexImage:SetColorAndOpacity(self.HandWeaponColor)
            UnhandWeaponIndexImage:SetColorAndOpacity(self.UnhandWeaponColor)

            local WeaponIcon, IsExistWeaponIcon = UE.UItemSystemManager.GetItemDataFString(self, 
            WeaponIndentity.ItemID, "FlowImage", GameDefine.NItemSubTable.Ingame,"ES_InfoPanel:UpdateData")
            if IsExistWeaponIcon then
                local ImageSoftObjectPtr = UE.UGFUnluaHelper.ToSoftObjectPtr(WeaponIcon)
                ImgWeaponIcon:SetBrushFromSoftTexture(ImageSoftObjectPtr)
            end

            local WeaponName, IsExistWeaponName = UE.UItemSystemManager.GetItemDataFText(self, 
            WeaponIndentity.ItemID, "ItemName", GameDefine.NItemSubTable.Ingame,"ES_InfoPanel:UpdateData")
            if IsExistWeaponName then
                TextWeaponName:SetText(StringUtil.Format(WeaponName))
            end
        end
    end
end

return ES_InfoPanel