---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bailixi.
--- DateTime: 2023/10/12 17:28
---

-- local RedDotConfg = require("Client.Modules.RedDot.RedDotConfig")
local RedDotConfg = {
    Enum_Style = {
        Normal          = "Normal",
        Number          = "Number",
        Text            = "Text",
    },
    
    UMG_Config = {
        ["Normal"] = {
            UMGPath = "/Game/BluePrints/UMG/OutsideGame/RedDot/WBP_RedDotNormalStyle.WBP_RedDotNormalStyle",
            LuaPath = "Client.Modules.RedDot.RedDotUMGStyles.RedDotUMGNormalStyle",
        },
        ["AdvancePoint"] = {
            UMGPath = "/Game/BluePrints/UMG/OutsideGame/RedDot/WBP_RedDotStrongStyle.WBP_RedDotStrongStyle",
            LuaPath = "Client.Modules.RedDot.RedDotUMGStyles.RedDotUMGNormalStyle",
        },
        ["Number"] = {
            UMGPath = "/Game/BluePrints/UMG/OutsideGame/RedDot/WBP_RedDotNumCountStyle.WBP_RedDotNumCountStyle",
            LuaPath = "Client.Modules.RedDot.RedDotUMGStyles.RedDotUMGNumCountStyle",
        },
        ["Text"] = {
            UMGPath = "/Game/BluePrints/UMG/OutsideGame/RedDot/WBP_RedDotTextStyle.WBP_RedDotTextStyle",
            LuaPath = "Client.Modules.RedDot.RedDotUMGStyles.RedDotUMGTextStyle",
        },
    }
}

return RedDotConfg